# Generated by Django 5.0.2 on 2024-03-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uplink', '0004_alter_link_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='order',
        ),
    ]
